### ISSUE TITLE
Test Spark on YARN

### ISSUE THREAD

**Issue by singarajus** [vangj/vagrant-hadoop-2.4.1-spark-1.0.1#1]
Document README

currently says:

$SPARK_HOME/bin/spark-submit --class org.apache.spark.examples.SparkPi \
    --master yarn-cluster \
    --num-executors 10 \
    --executor-cores 2 \
    lib/spark-examples*.jar \
    100

Should say:
$SPARK_HOME/bin/spark-submit --class org.apache.spark.examples.SparkPi \
    --master yarn-cluster \
    --num-executors 10 \
    --executor-cores 2 \
    $SPARK_HOME/lib/spark-examples*.jar \
    100

**Comment by vangj** [comment]
yes, you are right on that too. i was running from the spark install dir. but now the readme is updated per your finding.
