### ISSUE TITLE
Starting services

### ISSUE THREAD

**Issue by singarajus** [vangj/vagrant-hadoop-2.4.1-spark-1.0.1#2]
Hadoop starts from: /usr/local/hadoop. Services cannot be started as vagrant, but works as root.
The documentation should say login as root or the scripts/common.sh for locations need to be changed.
Please also identify how to start datanodes on node-3,node-4.

**Comment by vangj** [comment]
yes, you are right, you need to be root. i've updated that. datanodes on node3/4 should be started when running the yarn scripts.
